icons_format = ""

[theme]
name = "plain"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#bfbfbf"
separator = ""

[[block]]
block = "time"
interval = 5
format = " %a %d/%m %R"
on_click = "notify-send -u low -h string:x-canonical-private-synchronous:cal \"$(cal)\""
