#!/usr/bin/env sh

burger(){ curl -sL git.io/burger ;}
coffee(){ curl -sL git.io/coffee ;}
hotcoffee(){ curl -sL git.io/hotcoffee | sh ;}
pancakes(){ curl -sL git.io/pancakes ;}
pizzza(){ curl -sL git.io/pizzza ;}
poptart(){ curl -sL git.io/poptart ;}
rice(){ curl -sL rum.sh/ricebowl ;}
rice2(){ curl -sL http://git.io/rice ;}
vburger(){ curl -sL git.io/vburger ;}
waffles(){ curl -sL git.io/waffles ;}

case $1 in
    burger) burger ;;
    coffee) coffee ;;
    hotcoffee) hotcoffee ;;
    pancakes) pancakes ;;
    pizzza) pizzza ;;
    poptart) poptart ;;
    rice)  rice ;;
    rice2) rice2 ;;
    vburger) vburger ;;
    waffles) waffles ;;
    *)
        random=$(shuf -en1 burger coffee hotcoffee pancakes pizzza\
                      poptart rice rice2 vburger waffles)
        $random ;;
esac
